project_name: kustomize-sopssecretgenerator

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

env_files:
  github_token: .github_token

gomod:
  proxy: true

before:
  hooks:
    - go mod tidy

builds:
  - binary: SopsSecretGenerator
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: binary

changelog:
  filters:
    exclude:
      - '^Release version'
      - '^Merge pull request'

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: goabout
    name: kustomize-sopssecretgenerator
  name_template: "Version {{.Version}}"

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: .goreleaser.Dockerfile
    image_templates:
      - "goabout/kustomize-sopssecretgenerator:latest-amd64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}-amd64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}-amd64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
  - goos: linux
    goarch: arm64
    dockerfile: .goreleaser.Dockerfile
    image_templates:
      - "goabout/kustomize-sopssecretgenerator:latest-arm64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}-arm64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}-arm64"
      - "goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

docker_manifests:
  - name_template: goabout/kustomize-sopssecretgenerator:latest
    image_templates:
      - goabout/kustomize-sopssecretgenerator:latest-amd64
      - goabout/kustomize-sopssecretgenerator:latest-arm64
  - name_template: goabout/kustomize-sopssecretgenerator:v{{ .Major }}
    image_templates:
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}-amd64
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}-arm64
  - name_template: goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}-amd64
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - goabout/kustomize-sopssecretgenerator:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64
