# This CRD is not designed to be installed on a cluster, but is provided for IDE introspection
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sopssecretgenerators.freightdog.com
spec:
  group: freightdog.com
  names:
    kind: SopsSecretGenerator
    listKind: SopsSecretGeneratorList
    plural: sopssecretgenerators
    singular: sopssecretgenerator
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              enum:
                - freightdog.com/v1
            kind:
              type: string
              enum:
                - SopsSecretGenerator
            metadata:
              type: object
            behavior:
              type: string
              description: Defines the behavior of the secret generator (e.g., create, merge, replace)
            disableNameSuffixHash:
              type: boolean
              description: Disables the automatic name suffix hash.
            envs:
              type: array
              description: A list of environment variable files for generating secrets.
              items:
                type: string
            files:
              type: array
              description: A list of files and their mapping to generate secrets.
              items:
                type: string
            type:
              type: string
              description: Specifies the type of Kubernetes secret (e.g., Opaque, TLS).
